[tool.poetry]
name = "pydongo"
version = "0.1.0"
description = "A lightweight ORM for MongoDB using Pydantic models."
authors = ["Samuel Abolo <ikabolo59@gmil.com>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.9"
pymongo = "^4.11.3"
pydantic = "^2.10.6"
motor = "^3.7.0"

[tool.poetry.group.dev.dependencies]
mypy = "1.15.0"
ruff = "^0.11.0"
# pymongo = "^4.11.3"
# pydantic = "^2.10.6"

[build-system]
requires = ["poetry-core>=1.8.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
